# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  environment:
    - ELK_PRIVATE_KEY
    - ELK_CA
  ports:
    - 80:5601
    - 9200
    - 5044
  volumes:
    - elk-data:/var/lib/elasticsearch
